"""
Program Name: loadData.py
Program purpose: This program loads the LES data from the ouput_RAV files generated by Fabein Margairaz.

Program Author: Marc Calaf.

Date created: 05 March 2020
Last date modified: 11 August 2020

"""

# load_anisotropy(): is a function that loads the output RAV for the anisotropy module (phi3D,l3D,ustar3D,xB,yB)
#################################################################################################################
def load_anisotropy(Nx,Ny,Nz,NumVariables,NumIt,NumFiles,StartTime,path,vardata,anisotropy_flag=False):
    "Calling function to upload data from the Output_Rav files"

    import numpy as np
    import xarray as xr
    import struct
    import timeit

    print('Defining arrays')

    t0 = timeit.default_timer()

    tmp = np.zeros((Nx*Ny*Nz, 1),'d')  #This is a temporal variable used as a bridge.
    tmpdata = np.zeros((NumVariables*Nx*Ny*Nz),'d') #This is a temporal variable used as a bridge.
    sumdata = np.zeros((NumVariables*Nx*Ny*Nz),'d') #This is a temporal variable used as a bridge.

    t1 = timeit.default_timer()

    print('Loop over files')

    # Loop over the different RAV_output files:

    for n in range(0,NumFiles):
        if (StartTime + n*NumIt < 10000):
            FileName = 'RAV_00000'+ str(StartTime + n*NumIt) + '_aniso_3D.dat'
        elif (StartTime + n*NumIt < 100000) and (StartTime + n*NumIt >= 10000):
            FileName = 'RAV_0000'+ str(StartTime + n*NumIt) + '_aniso_3D.dat'
        elif (StartTime + n*NumIt < 1000000) and (StartTime + n*NumIt >= 100000):
            FileName = 'RAV_000'+ str(StartTime + n*NumIt) + '_aniso_3D.dat'
        else:
            FileName = 'RAV_00'+ str(StartTime + n*NumIt) + '_aniso_3D.dat'
            
        f = open(path+FileName,"rb")

        #Next we read the data and we dump it all, as strings into a new variable.


        print('Done reading the binari data for file = ', FileName)

        for i in range(0,NumVariables):

            data_raw = f.read(Nx*Ny*Nz*8)

            n0 = (i)*(Nx*Ny*Nz)
            nf = (i+1)*(Nx*Ny*Nz)

            #Next we read the strings from above into double-type numbers, that are stored in data.
            tmpdata[n0:nf] = np.array(struct.unpack('d'*(Nx*Ny*Nz), data_raw))


        #Now we can delete the main data matrix uploaded initially to free some memory
        del data_raw
        f.close()
        
        sumdata = sumdata + tmpdata
        
        print('Done computing the cumulative sum for data in file = ', FileName)


    print('Done adding the data')

    for i in range(0,NumVariables):
            print('Variable =', i)
            n0 = (i)*(Nx*Ny*Nz)
            nf = (i+1)*(Nx*Ny*Nz)
            tmp = sumdata[n0:nf]

            vardata[:,:,:,i] = np.reshape(tmp,[Nx,Ny,Nz],'F')


    del i,n,tmp


    return(vardata)
# load_tkevar(): is a function that loads the output RAV files for the tke budget variables
###############################################################################################

def load_tkevar(Nx,Ny,Nz,NumVariablesTKE,NumIt,NumFiles,StartTime,path,vardata):
    "Calling function to upload data from the Output_Rav files"

    import numpy as np
    import xarray as xr
    import struct
    import timeit
    
    # List of Variables that have been saved in the binary file 'Rav_output':
    #Variable = ['dudx','dudy','dudz','dvdx','dvdy','dvdz','dwdx','dwdy','dwdz',\
    #            'uv2','uw2','vu2','vw2','wu2','wv2','utxx','utyy','utzz',\
    #            'vtxx','vtyy','vtzz','wtxx','wtyy','wtzz',\    
    #            'pu1','pv1','pw1','pclean1',\
    #            'dxx','dyy','dzz','dxy','dxz','dyz',\
    #            'utxy','utxz','vtxy','vtyz','wtxz','wtyz',\
    #            'pu2','pv2','pw2','pu3','pv3','pw3','pclean2']
    
    print('Defining arrays')

    t0 = timeit.default_timer()

    # vardata = xr.DataArray(np.ones(shape = (Nx,Ny,Nz,NumVariablesTKE),order='F'),\
    #                     dims=('x', 'y','z','variable'), coords = {'variable':['avgDUDX','avgDUDY',\
    #                     'avgDUDZ','avgDVDX','avgDVDY','avgDVDZ','avgDWDX','avgDWDY','avgDWDZ',\
    #                     'avgUV2','avgUW2','avgVU2','avgVW2','avgWU2','avgWV2','avgUTXX',\
    #                     'avgUTYY','avgUTZZ','avgVTXX','avgVTYY','avgVTZZ','avgWTXX',\
    #                     'avgWTYY','avgWTZZ','avgPU1','avgPV1','avgPW1','avgPclean1',\
    #                     'avgdxx','avgdyy','avgdzz','avgdxy','avgdxz','avgdyz',\
    #                     'avgUTXY','avgUTXZ','avgVTXY','avgVTYZ','avgWTXZ','avgWTYZ',\
    #                     'avgPU2','avgPV2','avgPW2','avgPU3','avgPV3','avgPW3','avgPclean2']})
    
    tmp = np.zeros((Nx*Ny*Nz, 1),'d')  #This is a temporal variable used as a bridge.
    tmpdata = np.zeros((NumVariablesTKE*Nx*Ny*Nz),'d') #This is a temporal variable used as a bridge.
    sumdata = np.zeros((NumVariablesTKE*Nx*Ny*Nz),'d') #This is a temporal variable used as a bridge.

    t1 = timeit.default_timer()

    print('Loop over files')

    # Loop over the different RAV_output files:
    for n in range(0,NumFiles):

        if (StartTime + n*NumIt < 100000):
            FileName = 'RAV_tke_0000'+ str(StartTime + n*NumIt) + '_3D.dat'
        elif (StartTime + n*NumIt < 1000000) and (StartTime + n*NumIt >= 100000):
            FileName = 'RAV_tke_000'+ str(StartTime + n*NumIt) + '_3D.dat'
        else:
            FileName = 'RAV_tke_00'+ str(StartTime + n*NumIt) + '_3D.dat'
            
        f = open(path+FileName,"rb")

        #Next we read the data and we dump it all, as strings into a new variable.


        print('Done reading the binari data for file = ', FileName)

        for i in range(0,NumVariablesTKE):

            data_raw = f.read(Nx*Ny*Nz*8)

            n0 = (i)*(Nx*Ny*Nz)
            nf = (i+1)*(Nx*Ny*Nz)

            #Next we read the strings from above into double-type numbers, that are stored in data.
            tmpdata[n0:nf] = np.array(struct.unpack('d'*(Nx*Ny*Nz), data_raw))


        #Now we can delete the main data matrix uploaded initially to free some memory
        del data_raw
        f.close()

        sumdata = sumdata + tmpdata/(NumFiles*NumIt)
        
        print('Done computing the cumulative sum for data in file = ', FileName)





    print('Done adding the data')

    for i in range(0,NumVariablesTKE):
            print('Variable =', i)
            n0 = (i)*(Nx*Ny*Nz)
            nf = (i+1)*(Nx*Ny*Nz)
            tmp = sumdata[n0:nf]

            vardata[:,:,:,i] = np.reshape(tmp,[Nx,Ny,Nz],'F')


    del i,n,tmp


    return(vardata)

#################################################################################################################
def load_tkevarGigi(Nx,Ny,Nz,NumVariablesTKE,NumIt,NumFiles,StartTime,path,vardata):
    "Calling function to upload data from the Output_Rav files"

    import numpy as np
    import xarray as xr
    import struct
    import timeit
    
    # List of Variables that have been saved in the binary file 'Rav_output':
    #Variable = ['dudx','dudy','dudz','dvdx','dvdy','dvdz','dwdx','dwdy','dwdz',\
    #            'uv2','uw2','vu2','vw2','wu2','wv2','utxx','utyy','utzz',\
    #            'vtxx','vtyy','vtzz','wtxx','wtyy','wtzz',\    
    #            'pu1','pv1','pw1','pclean1',\
    #            'dxx','dyy','dzz','dxy','dxz','dyz',\
    #            'utxy','utxz','vtxy','vtyz','wtxz','wtyz',\
    #            'pu2','pv2','pw2','pu3','pv3','pw3','pclean2']
    
    print('Defining arrays')

    t0 = timeit.default_timer()

    # vardata = xr.DataArray(np.ones(shape = (Nx,Ny,Nz,NumVariablesTKE),order='F'),\
    #                     dims=('x', 'y','z','variable'), coords = {'variable':['avgU','avgV',\
    #                     'avgW','avgP','avgUU','avgVV','avgWW','avgUV','avgUW',\
    #                     'avgVW','avgDUDX','avgDUDY','avgDUDZ','avgDVDX','avgDVDY','avgDVDZ',\
    #                     'avgDWDX','avgDWDY','avgDWDZ','avgTXX','avgTYY','avgTZZ',\
    #                     'avgTXY','avgTXZ','avgTYZ','avgUUU','avgUVV','avgUWW',\
    #                     'avgVUU','avgVVV','avgVWW','avgWUU','avgWVV','avgWWW',\
    #                     'avgUTXX','avgUTYY','avgUTZZ','avgVTXX','avgVTYY','avgVTZZ',\
    #                     'avgWTXX','avgWTYY','avgWTZZ','avgVTXY','avgWTXZ','avgUTXY','avgWTYZ',\
    #                     'avgUTXZ','avgVTYZ','avgUP','avgVP','avgWP','avgDXX','avgDYY','avgDZZ',\
    #                     'avgDXY','avgDXZ','avgDYZ','avgFDX','avgFDY','avgFDZ','avgUFDX','avgVFDY','avgWFDZ']})
    
    tmp = np.zeros((Nx*Ny*Nz, 1),'d')  #This is a temporal variable used as a bridge.
    tmpdata = np.zeros((NumVariablesTKE*Nx*Ny*Nz),'d') #This is a temporal variable used as a bridge.
    sumdata = np.zeros((NumVariablesTKE*Nx*Ny*Nz),'d') #This is a temporal variable used as a bridge.

    t1 = timeit.default_timer()

    print('Loop over files')

    # Loop over the different RAV_output files:
    for n in range(0,NumFiles):
        if (StartTime + n*NumIt < 10000):
            FileName = 'RAV_00000'+ str(StartTime + n*NumIt) + '_3D.dat'
        elif (StartTime + n*NumIt < 100000) and (StartTime + n*NumIt >= 100000):
            FileName = 'RAV_0000'+ str(StartTime + n*NumIt) + '_3D.dat'
        elif (StartTime + n*NumIt < 1000000) and (StartTime + n*NumIt >= 100000):
            FileName = 'RAV_000'+ str(StartTime + n*NumIt) + '_3D.dat'
        else:
            FileName = 'RAV_00'+ str(StartTime + n*NumIt) + '_3D.dat'
            
        f = open(path+FileName,"rb")

        #Next we read the data and we dump it all, as strings into a new variable.


        print('Done reading the binari data for file = ', FileName)

        for i in range(0,NumVariablesTKE):

            data_raw = f.read(Nx*Ny*Nz*8)

            n0 = (i)*(Nx*Ny*Nz)
            nf = (i+1)*(Nx*Ny*Nz)

            #Next we read the strings from above into double-type numbers, that are stored in data.
            tmpdata[n0:nf] = np.array(struct.unpack('d'*(Nx*Ny*Nz), data_raw))


        #Now we can delete the main data matrix uploaded initially to free some memory
        del data_raw
        f.close()

        sumdata = sumdata + tmpdata/(NumFiles*NumIt)
        
        print('Done computing the cumulative sum for data in file = ', FileName)





    print('Done adding the data')

    for i in range(0,NumVariablesTKE):
            print('Variable =', i)
            n0 = (i)*(Nx*Ny*Nz)
            nf = (i+1)*(Nx*Ny*Nz)
            tmp = sumdata[n0:nf]

            vardata[:,:,:,i] = np.reshape(tmp,[Nx,Ny,Nz],'F')


    del i,n,tmp


    return(vardata)
    

# load_momentum(): is a function that loads the Output_Rav files for the momentum
##############################################################################

def load_momentum(Nx,Ny,Nz,NumVariables,NumIt,NumFiles,StartTime,path,vardata,anisotropy_flag=False):
    "Calling function to upload data from the Output_Rav files"

    import numpy as np
    import xarray as xr
    import struct
    import timeit
    #import math

    # List of Variables that have been saved in the binary file 'Rav_output':
    #Variable = ['u','v','w','p','u2','v2','w2','u3','v3','w3','u4','v4','w4',\
    #            'uv','uw','vw','txx','tyy','tzz','txy','txz','tyz',\
    #            'dudz','dvdz','nut','cs']

    print('Defining arrays')

    t0 = timeit.default_timer()

    # vardata = xr.DataArray(np.ones(shape = (Nx,Ny,Nz,NumVariables),order='F'),\
    #                     dims=('x', 'y','z','variable'), coords = {'variable':['avgU','avgV',\
    #                     'avgW','avgP','avgU2','avgV2','avgW2','avgU3','avgV3',\
    #                     'avgW3','avgU4','avgV4','avgW4','avgUV','avgUW','avgVW',\
    #                     'avgtxx','avgtyy','avgtzz','avgtxy','avgtxz','avgtyz',\
    #                     'avgdudz','avgdvdz','avgNut','avgCs']})


    tmp = np.zeros((Nx*Ny*Nz, 1),'d')  #This is a temporal variable used as a bridge.
    tmpdata = np.zeros((NumVariables*Nx*Ny*Nz),'d') #This is a temporal variable used as a bridge.
    sumdata = np.zeros((NumVariables*Nx*Ny*Nz),'d') #This is a temporal variable used as a bridge.

    t1 = timeit.default_timer()

    print('Loop over files')

    # Loop over the different RAV_output files:

    for n in range(0,NumFiles):
        if (StartTime + n*NumIt < 10000):
            FileName = 'RAV_00000'+ str(StartTime + n*NumIt) + '_3D.dat'
        elif (StartTime + n*NumIt < 100000) and (StartTime + n*NumIt >= 10000):
            FileName = 'RAV_0000'+ str(StartTime + n*NumIt) + '_3D.dat'
        elif (StartTime + n*NumIt < 1000000) and (StartTime + n*NumIt >= 100000):
            FileName = 'RAV_000'+ str(StartTime + n*NumIt) + '_3D.dat'
        else:
            FileName = 'RAV_00'+ str(StartTime + n*NumIt) + '_3D.dat'
            
        f = open(path+FileName,"rb")

        #Next we read the data and we dump it all, as strings into a new variable.


        print('Done reading the binari data for file = ', FileName)

        for i in range(0,NumVariables):

            data_raw = f.read(Nx*Ny*Nz*8)

            n0 = (i)*(Nx*Ny*Nz)
            nf = (i+1)*(Nx*Ny*Nz)

            #Next we read the strings from above into double-type numbers, that are stored in data.
            tmpdata[n0:nf] = np.array(struct.unpack('d'*(Nx*Ny*Nz), data_raw))


        #Now we can delete the main data matrix uploaded initially to free some memory
        del data_raw
        f.close()
        
        sumdata = sumdata + tmpdata/(NumFiles*NumIt)
        
        print('Done computing the cumulative sum for data in file = ', FileName)


    print('Done adding the data')

    for i in range(0,NumVariables):
            print('Variable =', i)
            n0 = (i)*(Nx*Ny*Nz)
            nf = (i+1)*(Nx*Ny*Nz)
            tmp = sumdata[n0:nf]

            vardata[:,:,:,i] = np.reshape(tmp,[Nx,Ny,Nz],'F')


    del i,n,tmp


    return(vardata)

##############################################################################
##############################################################################
##############################################################################


# load_scalar(): is a function that loads the Output_Rav files for the scalar
##############################################################################

def load_scalar(Nx,Ny,Nz,NumVariablesSC,NumIt,NumFiles,StartTime,path,vardataS):
    "Calling function to upload data from the Output_Rav_SC files"

    import numpy as np
    import xarray as xr
    import struct
    import timeit

    # List of Variables that have been saved in the binary file 'Rav_output':
    #Variable = ['T','T2','uT','vT','wT','uT_sgs','vT_sgs','wT_sgs','nus','ds'};]

    print('Defining arrays')

    # vardataS = xr.DataArray(np.ones(shape = (Nx,Ny,Nz,NumVariablesSC),order='F'),\
    #                     dims=('x','y','z','variable'), coords = {'variable':['avgT','avgT2',\
    #                     'avgUT','avgVT','avgWT','avgUT_sgs','avgVT_sgs','avgWT_sgs','avg_nus',\
    #                     'avg_ds']})

    tmp = np.zeros((Nx*Ny*Nz, 1),'d')  #This is a temporal variable used as a bridge.
    tmpdata = np.zeros((NumVariablesSC*Nx*Ny*Nz),'d') #This is a temporal variable used as a bridge.
    sumdata = np.zeros((NumVariablesSC*Nx*Ny*Nz),'d') #This is a temporal variable used as a bridge.

    print('Loop over files')

    for n in range(0,NumFiles):
        if (StartTime + n*NumIt < 10000):
            FileName = 'RAV_00000'+ str(StartTime + n*NumIt) + '_SC_3D.dat'
        elif (StartTime + n*NumIt < 100000) and (StartTime + n*NumIt >= 10000):
            FileName = 'RAV_0000'+ str(StartTime + n*NumIt) + '_SC_3D.dat'
        elif (StartTime + n*NumIt < 1000000) and (StartTime + n*NumIt >= 100000):
            FileName = 'RAV_000'+ str(StartTime + n*NumIt) + '_SC_3D.dat'
        else:
            FileName = 'RAV_00'+ str(StartTime + n*NumIt) + '_SC_3D.dat'
            
        f = open(path+FileName,"rb")

        #Next we read the data and we dump it all, as strings into a new variable.


        print('Done reading the binari data for file = ', n)

        for i in range(0,NumVariablesSC):

            data_raw = f.read(Nx*Ny*Nz*8)

            n0 = (i)*(Nx*Ny*Nz)
            nf = (i+1)*(Nx*Ny*Nz)

            #Next we read the strings from above into double-type numbers, that are stored in data.
            tmpdata[n0:nf] = np.array(struct.unpack('d'*(Nx*Ny*Nz), data_raw))


        #Now we can delete the main data matrix uploaded initially to free some memory
        del data_raw
        f.close()

        sumdata = sumdata + tmpdata/(NumFiles*NumIt)


    print('Done adding the data')

    for i in range(0,NumVariablesSC):
            print('Variable =', i)
            n0 = (i)*(Nx*Ny*Nz)
            nf = (i+1)*(Nx*Ny*Nz)
            tmp = sumdata[n0:nf]

            vardataS[:,:,:,i] = np.reshape(tmp,[Nx,Ny,Nz],'F')

    del i,n,tmp


    return(vardataS)


##############################################################################
##############################################################################
##############################################################################


# load_scalar_2D(): is a function that loads the 2D Output_Rav files for the scalars
##############################################################################

def load_scalar_2D(Nx,Ny,NumVariables_2D_SC,NumIt,NumFiles,StartTime,path,vardata):

    import numpy as np
    import xarray as xr
    import struct


    print('Defining arrays')


    # vardata = xr.DataArray(np.ones(shape = (Nx,Ny,NumVariables_2D_SC),order='F'),\
    #                 dims=('x','y','variable'), coords = {'variable':['Mav_wstar','Mav_L',\
    #                 'Mav_phi_m','Mav_psi_m','Mav_phi_h','Mav_psi_h','Mav_sfcval','Mav_sfcflux']})
    
    tmpdata = np.zeros((NumVariables_2D_SC*Nx*Ny),'d') #This is a temporal variable used as a bridge.
    sumdata = np.zeros((NumVariables_2D_SC*Nx*Ny),'d') #This is a temporal variable used as a bridge.
    tmp = np.zeros((Nx*Ny, 1),'d')  #This is a temporal variable used as a bridge.



    for n in range(0,NumFiles):
        if (StartTime + n*NumIt < 10000):
            FileName = 'RAV_00000'+ str(StartTime + n*NumIt) + '_SC_2D.dat'
        elif (StartTime + n*NumIt < 100000) and (StartTime + n*NumIt >= 10000):
            FileName = 'RAV_0000'+ str(StartTime + n*NumIt) + '_SC_2D.dat'
        elif (StartTime + n*NumIt < 1000000) and (StartTime + n*NumIt >= 100000):
            FileName = 'RAV_000'+ str(StartTime + n*NumIt) + '_SC_2D.dat'
        else:
            FileName = 'RAV_00'+ str(StartTime + n*NumIt) + '_SC_2D.dat'
            
        f = open(path+FileName,"rb")

        #Next we read the data and we dump it all, as strings into a new variable.
        print('Done reading the binari data for file = ', FileName)


        for i in range(0,NumVariables_2D_SC):

            data_raw = f.read(Nx*Ny*8)

            n0 = (i)*(Nx*Ny)
            nf = (i+1)*(Nx*Ny)

            #Next we read the strings from above into double-type numbers, that are stored in data.
            tmpdata[n0:nf] = np.array(struct.unpack('d'*(Nx*Ny), data_raw))

        #Now we can delete the main data matrix uploaded initially to free some memory
        del data_raw
        f.close()

        sumdata = sumdata + tmpdata/(NumFiles*NumIt)

    
    print('Done adding the data')
    
    for i in range(0,NumVariables_2D_SC):
        print('Variable =', i)
        n0 = (i)*(Nx*Ny)
        nf = (i+1)*(Nx*Ny)
        tmp = sumdata[n0:nf]

        vardata[:,:,i] = np.reshape(tmp,[Nx,Ny],'F')


    del i,n,tmp


    return(vardata)


##############################################################################
##############################################################################
##############################################################################

# load_momentum_2D(): is a function that loads the 2D Output_Rav files for the scalars
##############################################################################

def load_momentum_2D(Nx,Ny,NumVariables_2D,NumIt,NumFiles,StartTime,path,vardata):

    import numpy as np
    import xarray as xr
    import struct


    print('Defining arrays')


    # vardata = xr.DataArray(np.ones(shape = (Nx,Ny,NumVariables_2D),order='F'),\
    #                 dims=('x','y','variable'), coords = {'variable':['Mav_ustar']})
    
    tmpdata = np.zeros((NumVariables_2D*Nx*Ny),'d') #This is a temporal variable used as a bridge.
    sumdata = np.zeros((NumVariables_2D*Nx*Ny),'d') #This is a temporal variable used as a bridge.
    tmp = np.zeros((Nx*Ny, 1),'d')  #This is a temporal variable used as a bridge.



    for n in range(0,NumFiles):
        if (StartTime + n*NumIt < 10000):
            FileName = 'RAV_00000'+ str(StartTime + n*NumIt) + '_2D.dat'
        elif (StartTime + n*NumIt < 100000) and (StartTime + n*NumIt >= 10000):
            FileName = 'RAV_0000'+ str(StartTime + n*NumIt) + '_2D.dat'
        elif (StartTime + n*NumIt < 1000000) and (StartTime + n*NumIt >= 100000):
            FileName = 'RAV_000'+ str(StartTime + n*NumIt) + '_2D.dat'
        else:
            FileName = 'RAV_00'+ str(StartTime + n*NumIt) + '_2D.dat'
        
        f = open(path+FileName,"rb")

        #Next we read the data and we dump it all, as strings into a new variable.
        print('Done reading the binari data for file = ', FileName)


        for i in range(0,NumVariables_2D):

            data_raw = f.read(Nx*Ny*8)

            n0 = (i)*(Nx*Ny)
            nf = (i+1)*(Nx*Ny)

            #Next we read the strings from above into double-type numbers, that are stored in data.
            tmpdata[n0:nf] = np.array(struct.unpack('d'*(Nx*Ny), data_raw))

        #Now we can delete the main data matrix uploaded initially to free some memory
        del data_raw
        f.close()

        sumdata = sumdata + tmpdata/(NumFiles*NumIt)

    
    print('Done adding the data')
    
    for i in range(0,NumVariables_2D):
        print('Variable =', i)
        n0 = (i)*(Nx*Ny)
        nf = (i+1)*(Nx*Ny)
        tmp = sumdata[n0:nf]

        vardata[:,:,i] = np.reshape(tmp,[Nx,Ny],'F')


    del i,n,tmp


    return(vardata)

##############################################################################
##############################################################################
##############################################################################

# load_2Dfield(): is a function that loads the Input 2D Surface temperature fields
##############################################################################

def load_2Dfield(Nx,Ny,path):
    "Calling function to upload data from the Output_Rav_SC files"

    import numpy as np
    import struct


    print('Defining arrays')

    SurfTemp = np.zeros((Nx*Ny),'d')   #This is a temporal variable used as a bridge.
    SurfTemp2D = np.zeros((Nx,Ny),'d') #This is the final variable where the 2D field is stored.

    print('Opening the Surface Temperature file')


    FileName = '../input/surface_SC1.dat'
    f = open(path+FileName,"rb")

    #Next we read the data and we dump it all, as strings into a new variable.

    print('Done reading the binari data')

    data_raw = f.read(Nx*Ny*8)


    #Next we read the strings from above into double-type numbers, that are stored in data.
    SurfTemp[0:(Nx*Ny)] = np.array(struct.unpack('d'*(Nx*Ny), data_raw))
    SurfTemp2D[:,:] = np.reshape(SurfTemp,[Nx,Ny],'F')

    #Now we can delete the main data matrix uploaded initially to free some memory
    del data_raw
    f.close()



    return(SurfTemp2D)


##############################################################################
##############################################################################
##############################################################################


# load_snapshot(): is a function that loads the Snapshot files from Fabien's LES
##############################################################################

def load_snapshot(Nx,Ny,Nz,NumVariables,file_name,path):
    "Calling function to upload data from the Output_Rav files"

    import numpy as np
    import xarray as xr
    import struct


    # List of Variables that have been saved in the binary file 'snapshots_000XXXXXX.dat':
    #Variables = ['u','v','w','T']

    print('Defining DataArray')

    vardata = xr.DataArray(np.ones(shape = (Nx,Ny,Nz,NumVariables),order='F'),\
                           dims=('x', 'y','z','variable'), coords = {'variable':['U','V','W','T']})

    tmp = np.zeros((Nx*Ny*Nz, 1),'d')  #This is a temporal variable used as a bridge.
    tmpdata = np.zeros((NumVariables*Nx*Ny*Nz),'d') #This is a temporal variable used as a bridge.

    FileName = file_name
    f = open(path+FileName,"rb")

    #Next we read the data and we dump it all, as strings into a new variable.

    for i in range(0,NumVariables):

        data_raw = f.read(Nx*Ny*Nz*8)

        n0 = (i)*(Nx*Ny*Nz)
        nf = (i+1)*(Nx*Ny*Nz)

        #Next we read the strings from above into double-type numbers, that are stored in data.
        tmpdata[n0:nf] = np.array(struct.unpack('d'*(Nx*Ny*Nz), data_raw))


    #Now we can delete the main data matrix uploaded initially to free some memory
    del data_raw
    f.close()

        
    for i in range(0,NumVariables):
        print('Variable =', i)
        n0 = (i)*(Nx*Ny*Nz)
        nf = (i+1)*(Nx*Ny*Nz)
        tmp = tmpdata[n0:nf]

        vardata[:,:,:,i] = np.reshape(tmp,[Nx,Ny,Nz],'F')


    del i,tmp


    return(vardata)

##############################################################################
##############################################################################
##############################################################################